### ISSUE TITLE
demo apk not working

### ISSUE THREAD

**Issue by NazarK** [cranberrygame/cordova-plugin-ad-video-chartboost#1]
provided demo apk doesn't show ads.

seems chartboost changed something, I've tested other two plugins and they don't work too.

would be nice to have some debug output from this plugin.

**Comment by NazarK** [comment]
sorry, it just needs to wait some time. then it logs "setUp succeeded". and ads are showing after that.

**Comment by cranberrygame** [comment]
@NazarK
Ok
Thanks
