### ISSUE TITLE
Build error in CocoonIO

### ISSUE THREAD

**Issue by AndreasReitberger** [cranberrygame/cordova-plugin-ad-video-chartboost#11]
Since the latest update of Cocoon, the chartboost plugins Chartboost plugin causes build crashes.
Here is the error log.

Removed LAUNCHER flag
ANDROID_HOME=opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-linux
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
null
org.xwalk:xwalk_core_library:19+
Not writing assets/xwalk-command-line since file already exists.
:preBuild UP-TO-DATE
:preArmv7ReleaseBuild UP-TO-DATE
:checkArmv7ReleaseManifest
:preX86ReleaseBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:compileReleaseAidl
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareAndroidCordovaLibUnspecifiedReleaseLibrary
:preArmv7DebugBuild UP-TO-DATE
:preX86DebugBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:compileDebugAidl
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:prepareCanvasplusReleaseLibrary
:prepareComAndroidSupportAppcompatV72311Library
:prepareComAndroidSupportMultidex101Library
:prepareComAndroidSupportSupportV42400Beta1Library
:prepareComFacebookAndroidFacebookAndroidSdk481Library
:prepareComGoogleAndroidGmsPlayServicesAds902Library
:prepareComGoogleAndroidGmsPlayServicesAdsLite902Library
:prepareComGoogleAndroidGmsPlayServicesAnalytics902Library
:prepareComGoogleAndroidGmsPlayServicesAnalyticsImpl902Library
:prepareComGoogleAndroidGmsPlayServicesAuthBase902Library
:prepareComGoogleAndroidGmsPlayServicesBase902Library
:prepareComGoogleAndroidGmsPlayServicesBasement902Library
:prepareComGoogleAndroidGmsPlayServicesDrive902Library
:prepareComGoogleAndroidGmsPlayServicesGames902Library
:prepareComGoogleAndroidGmsPlayServicesPlus902Library
:prepareComGoogleAndroidGmsPlayServicesTasks902Library
:prepareComGoogleFirebaseFirebaseCommon902Library
:prepareComSegmentAnalyticsAndroidAnalytics414Library
:prepareDevapplibReleaseLibrary
:prepareOrgXwalkXwalk_core_library19495144Library
:prepareWebviewplusReleaseLibrary
:prepareArmv7ReleaseDependencies
:compileArmv7ReleaseAidl
:compileArmv7ReleaseRenderscript
:generateArmv7ReleaseBuildConfig
:generateArmv7ReleaseAssets UP-TO-DATE
:mergeArmv7ReleaseAssets
:generateArmv7ReleaseResValues
:generateArmv7ReleaseResources
:mergeArmv7ReleaseResources
AAPT: cordova/platforms/android/build/intermediates/exploded-aar/devapplib-release/res/mipmap-mdpi/ic_back_b.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: cordova/platforms/android/build/intermediates/exploded-aar/devapplib-release/res/mipmap-xhdpi/ic_back_b.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: cordova/platforms/android/build/intermediates/exploded-aar/devapplib-release/res/mipmap-xhdpi/ic_back_w.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: cordova/platforms/android/build/intermediates/exploded-aar/devapplib-release/res/mipmap-mdpi/ic_back_w.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: cordova/platforms/android/build/intermediates/exploded-aar/devapplib-release/res/drawable/detail_default.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: cordova/platforms/android/build/intermediates/exploded-aar/devapplib-release/res/mipmap-hdpi/ic_back_b.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: cordova/platforms/android/build/intermediates/exploded-aar/devapplib-release/res/mipmap-hdpi/ic_back_w.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: cordova/platforms/android/build/intermediates/exploded-aar/devapplib-release/res/mipmap-xxhdpi/ic_back_w.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: cordova/platforms/android/build/intermediates/exploded-aar/devapplib-release/res/mipmap-xxhdpi/ic_back_b.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
:processArmv7ReleaseManifest
:processArmv7ReleaseResources
:generateArmv7ReleaseSources
:compileArmv7ReleaseJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:compileArmv7ReleaseNdk UP-TO-DATE
:compileArmv7ReleaseSources
:lintVitalArmv7Release
:transformClassesWithDexForArmv7Release
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:484)
at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:261)
at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:473)
at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:161)
at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
at com.android.dx.command.dexer.Main.run(Main.java:277)
at com.android.dx.command.dexer.Main.main(Main.java:245)
at com.android.dx.command.Main.main(Main.java:106)

FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':transformClassesWithDexForArmv7Release'.
  
  > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 2
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8 mins 55.324 secs
ERROR building one of the platforms: Error code 1 for command: cordova/platforms/android/gradlew with args: cdvBuildRelease,-b,cordova/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true
You may not have the required environment or OS to build this project
Error: Error code 1 for command: cordova/platforms/android/gradlew with args: cdvBuildRelease,-b,cordova/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true

If I remove the plugin, the built works fine.

Thank you!

**Comment by cranberrygame** [comment]
@AndreasReitberger 

Hi,

Tested build but no build error.

Thanks
Sang Ki Kwon
