### ISSUE TITLE
App crashes on startup using this plugin

### ISSUE THREAD

**Issue by AndreasReitberger** [cranberrygame/cordova-plugin-ad-video-chartboost#16]
Hi @cranberrygame 
sadly this plugin causes the application to crash on startup (Intel XDK and CocoonIO).
I tried it on Android only at the moment. Is there a way to get it fixed?

Thank you!

**Comment by acheo** [comment]
Possibly related?

https://stackoverflow.com/questions/40893299/app-crash-when-i-run-window-chartboost-setup-appid-appsignature-with-ionic

**Comment by acheo** [comment]
Got it working:
https://github.com/acheo/cordova-plugin-ad-chartboost/commit/e38540964c92fbf5172441a5d94a42e7781e749c

I noticed that it doesn't crash in the cocoon dev app but does crash in a normal build without a google play services reference. I'm not entirely sure of the most appropriate version to include at the moment.

I guess building a dev app includes that reference automatically somehow?
