### ISSUE TITLE
Different actions based on location parameter?

### ISSUE THREAD

**Issue by iamaro** [cranberrygame/cordova-plugin-ad-video-chartboost#3]
Hey There,

I'm trying to display a fullscreen ad in two different places, and I'd like to have different stuff happen in the callback depending on which ad was called.

As of now, I'm not sure how to differentiate between the two -- does the 'location' parameter have anything to do with this?

Thanks,
Clay

**Comment by cranberrygame** [comment]
@iamaro 

Added location parameter feature to callback event.

You can use this parameter to detect which location is used.
Thanks
