### ISSUE TITLE
"setup failed"  error

### ISSUE THREAD

**Issue by abdulmaalik** [cranberrygame/cordova-plugin-ad-video-chartboost#6]
i have tried to execute your demo project but it says 
"setUp failed"
kindly help me to resolve this issue thanks

**Comment by cranberrygame** [comment]
@abdulmaalik 

Fixed the issue.
Check it.
Thanks

**Comment by abdulmaalik** [comment]
thank you for your quick response i really appreciate that. i will test this later on
